name: CI

on:
  push:
    branches: [ "develop", "feature/compiler" ]

  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt install -y clang
          git submodule update --init --recursive compiler/lib/googletest
          cd compiler
          chmod +x ./build.sh
          ./build.sh

      - name: Test
        run: |
          cd compiler
          build/bin/ddlbx_test
          python3 test/integration_test.py
