name: CI

on:
  push:
    branches: [ "develop", "feature/compiler" ]
    
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          git submodule update --init --recursive
          cd compiler
          chmod +x ./build.sh
          ./build.sh

      - name: Test
        run:
          compiler/build/bin/ddlbx_test